.TH DRAWER 1 "2022 Jul 23"
.SH NAME
drawer \- a simple datadesk interpreter made in C
.SH SYNOPSIS
.br
.B drawer
[options] [file ..]
.br
.SH DESCRIPTION
.B DRAWER
is a datadesk interpreter focused on speed and efficiency.
it also server as a reference interpreter
.PP
Drawer includes a demo file placed inside the "/etc/datadesk" directory.
.SH SEE ALSO
https://zesrajsie.tk/blog/blog6.html
.SH AUTHOR
Most of
.B Drawer (and datadesk itself)
was made by M4kulatura, with a lot of help from others.
.SH BUGS
Probably.
